### PR TITLE
Feature/add properties to models

### PR DESCRIPTION
**Pull request by belcurv**
Adds Mongoose user schema property: 'avatar_url' to user model.
Adds 'avatar_url' object property to auth route 'register' .

Adds Mongoose post schema property 'active' to post model.
Adds 'active' object property to post 'update' API route.
Adds 'avatar_url' object property to API route 'update user profile'.

### CODE REVIEW

**Comment by genestd** [comment]
Jay - I think the register URL is a little heavy.  How much detail do you want the user to provide in order to register?  My initial component was just username and password.  That would be enough to create an account, and then all the other preferences could be set on the edit profile route

**Comment by belcurv** [comment]
@genest - only the username and password are required. The other properties are technically optional. So yeah, initial registration could just be username and password.

**Comment by belcurv** [comment]
@genestd - I have seen the light. You're right. I will slim down the 'register' route and move the user detail bits to the user profile update API route.
*Please don't merge this PR yet!*

**Comment by belcurv** [comment]
@genestd - please review when convenient.

**Pull request merged**
